CREATE DATABASE THAOTAC_BANG;
USE THAOTAC_BANG;
CREATE TABLE NHAN_VIEN
( MA_NHAN_VIEN INT(10) NOT NULL AUTO_INCREMENT,
  TEN_NHAN_VIEN VARCHAR(30) NOT NULL,
  NGAY_SINH DATE,
  CONSTRAINT NHAN_VIEN PRIMARY KEY (MA_NHAN_VIEN)
);
ALTER TABLE NHAN_VIEN
ADD MO_TA varchar(50);
ALTER TABLE NHAN_VIEN
DROP column MO_TA;
ALTER TABLE NHAN_VIEN
  RENAME TO NHAN_VIEN_CONG_TY;
DROP table NHAN_VIEN;